### ISSUE TITLE
Creación Proyecto SC -Segunda Revisión

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/AdministracionAltoRendimiento2017#17]
Esta tarea consiste en crear un proyecto de productos de  ## Recurso Humano Técnico
  ## y de Organización de Competencias

@danteghirardelli Favor de crear el proyecto y ir subiendo las imágenes en esta misma tarea.

**Comment by danteghirardelli** [comment]
@felipedonoso 
A continuación imágenes del Proyecto "Stark Industries" Creado:

![image](https://cloud.githubusercontent.com/assets/21196249/18474736/f32f3980-7999-11e6-9259-ede489940dcb.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18474782/227f759c-799a-11e6-8439-85eb18d8f785.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18474786/2f3d9ebc-799a-11e6-8e45-f8af8e73ec5d.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18474799/3a17fd3c-799a-11e6-9c02-aaf1d27dbf66.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18474810/47019a6c-799a-11e6-89d9-39d6ca3f3556.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18474882/9ecfa0ea-799a-11e6-9405-681e0acc9be0.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18474890/a5fb9a68-799a-11e6-98e2-a0c44eab02cf.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18474895/aeb52782-799a-11e6-96da-e2f0e2ff1fc5.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18474908/b85c6eda-799a-11e6-844a-4da7b771de61.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18474920/cb26265a-799a-11e6-9043-61621748ff60.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18474927/d48a1ada-799a-11e6-8eed-86d134aa83ea.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18474933/dd3bc2f0-799a-11e6-9e3d-88ca863195f9.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18474946/eb144438-799a-11e6-8da1-e6b731dbf929.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18474953/f16ccba2-799a-11e6-841f-2957ccb50523.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18474960/f9e48522-799a-11e6-83a8-c8ce1b3a88ef.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18474987/13466b98-799b-11e6-93a4-6edf22bdbbc5.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18475001/2444f3f6-799b-11e6-93f8-3af29ea63401.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18475014/2feaf5ac-799b-11e6-8c7e-59455b95aaf5.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18475019/3565b972-799b-11e6-9616-462e628ca201.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18475024/3d4afe22-799b-11e6-91d4-350e5e5b2e5f.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18475037/4882769e-799b-11e6-8661-87ade2d08bbc.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18475041/4f9fbbbc-799b-11e6-9ac6-be9ba01572c9.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18475047/5933caec-799b-11e6-9b82-332afb5f3380.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18475089/966996b2-799b-11e6-8fdc-91c1c579c0a3.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18475098/9dab73aa-799b-11e6-8111-03e4e4a64817.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18475107/aa1e25ce-799b-11e6-990e-e63b43465a5b.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18475143/ca8d38ea-799b-11e6-86f5-8199911d71ec.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18475153/d1a0c84a-799b-11e6-8b84-9f1cabc8fbd6.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18475164/d902bb84-799b-11e6-8c46-3f0dcd01add5.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18475184/e65a3898-799b-11e6-96d7-15f6bac4948b.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18475195/ec4d8e8a-799b-11e6-9a34-54ba8a5f3421.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18475204/f2145092-799b-11e6-97a7-a76ea616a283.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18475213/f7e61cf8-799b-11e6-99c7-a23802d2517f.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18475222/ffd4e53e-799b-11e6-8cc0-8c0a2fab3895.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18475236/09b8caac-799c-11e6-98d2-01e2833371d5.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18475249/1398a3c6-799c-11e6-85ed-8a9b7a7e93a1.png)

![image](https://cloud.githubusercontent.com/assets/21196249/18475260/1e0afb9c-799c-11e6-874d-993e11355081.png)

Este quedó listo para "Postular".

**Comment by felipedonoso** [comment]
@danteghirardelli , esperemos que liberen la versión y continuamos con las pruebas.

### Gracias,

**Comment by danteghirardelli** [comment]
@felipedonoso 

De nada amigo.
Para eso estamos.
Saludos.
