### ISSUE TITLE
Reporte Alto Rendimiento - converges

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/AdministracionAltoRendimiento2017#2]
Este reporte entregará la siguiente información:

![image](https://cloud.githubusercontent.com/assets/5757157/17897027/fef0adde-6928-11e6-98d7-02c6e07f6163.png)

Se adjunta presentación en ppt para mayor información.

[Reporte por Federaciones (1).pptx](https://github.com/InstitutoNacionalDeDeportes/AdministracionAltoRendimiento2017/files/432696/Reporte.por.Federaciones.1.pptx)

**Comment by pabloespinoza** [comment]
- Reporte disponible en ambiente QA.  
- Link a reporte disponible en AdministracionQA. Ruta: Asignacion Recursos -> Link "Ver reporte general de Líneas"

**Comment by felipedonoso** [comment]
Andy solicitará a Edson Maya para que tenga el respaldo de producción hacia TESTINDW, yo realizare las pruebas de los montos una vez que tenga dicho respaldo.

Dante revisará que el formato sea como el mockup presentado.

**Comment by danteghirardelli** [comment]
Los Títulos Alto Rendimiento y Converges.
Según petición del Cliente deben quedar siempre sobre el Resumen de Línea siguiente.

Como observación en el Resumen de la Línea 121240133442 Nombre de Línea "Apoyo Especial a Deportistas" no aparecen del mismo tamaño entre Alto Rendimiento y Converges.

Respecto a la comparación de campos estos están idénticos.

Adjunto Archivo.
[Rev ReporteResumLinvsConverges_240816.docx](https://github.com/InstitutoNacionalDeDeportes/AdministracionAltoRendimiento2017/files/435023/Rev.ReporteResumLinvsConverges_240816.docx)

**Comment by pabloespinoza** [comment]
Las observaciones se encuentran corregidas y publicadas en ambiente QA

**Comment by felipedonoso** [comment]
Se solicito respaldo de producción al testing con las fechas más próximas al respaldo de converges para poder tener los datos más cercanos a producción.

![captura de pantalla 2016-08-25 a las 13 58 15](https://cloud.githubusercontent.com/assets/5757157/17976240/00215604-6ac3-11e6-9a7c-da6a983b7d1c.png)

**Comment by felipedonoso** [comment]
Pablo ahora esta listo el respaldo favor de apuntar a esta base de datos que esta más actualizada.

![image](https://cloud.githubusercontent.com/assets/5757157/17982857/1d6cf9d0-6ae0-11e6-9ded-29e01c3b2e67.png)

**Comment by pabloespinoza** [comment]
Cambio realizado.

**Comment by felipedonoso** [comment]
Pablo al revisar en Converges encontré los siguientes detalles:

 
![image](https://cloud.githubusercontent.com/assets/5757157/17984065/248b135e-6ae6-11e6-9025-d9053cd9a06b.png)

Y en Converges:

![image](https://cloud.githubusercontent.com/assets/5757157/17984410/5b1d5930-6ae7-11e6-9f3b-f573fdb526d5.png)

Te comento que ya les solicite a Andy los permisos tanto para dejar en Desarrollo el Web services como el rol de Administrador en tú equipo.

![image](https://cloud.githubusercontent.com/assets/5757157/17984451/953c30a0-6ae7-11e6-976c-128a36df65fe.png)

**Comment by felipedonoso** [comment]
Pablo puedes apuntar el reporte por el lado de las líneas presupuestarias a la Base de datos:

![image](https://cloud.githubusercontent.com/assets/5757157/18002863/e0cf6a0e-6b60-11e6-87e4-d1457c119ccd.png)


Lo otro me indica Andy que ya tienes los permisos para poder publicar el WS y permisos como administrador en tú equipo.

![image](https://cloud.githubusercontent.com/assets/5757157/18002900/1d0e1146-6b61-11e6-9fa7-806c30485298.png)

Avísame, cuando este lista la publicación.

**Comment by felipedonoso** [comment]
Pablo al revisar, el reporte coincide con los montos en Converges, lo que sí en vez de mostrar en un link  necesito que aparezca como un botón:

Para el botón, ejemplo, en vez de información debería decir  Reporte Converges:



![image](https://cloud.githubusercontent.com/assets/5757157/18009620/775a7320-6b83-11e6-89ba-374f7a0cd934.png)


![image](https://cloud.githubusercontent.com/assets/5757157/18009579/3f27c6e2-6b83-11e6-87c6-02c826c7e19f.png)



Para la revisión en Converges fue de esta manera:

**--seleccionados**
_select sum(monto) as monto 
from hda_proyecto
where proyecto like '16%' and  
cuenta='1212401337424' and estado=6-- or annio=2016_

**--Aprobado**
_select sum(monto) as monto 
from hda_proyecto
where proyecto like '16%' and  
cuenta='1212401337424' and estado=8-- or annio=2016_
**--CvgCuotas**
_select * from cvg_cuotas where ano=2016 and  
cuenta='1212401337424'_

-- sistema
**Monto Total Línea:** 
$7.086.633.000  7.086.633.000
Total Seleccionado: 
$80.447.757 80.447.757 ok
**Total Aprobado:** 
$6.222.041.647 6.222.041.647 ok
**Total Disponible:** 
$784.143.596

Ahora revisare los montos del Alto Rendimiento.

**Comment by felipedonoso** [comment]
Al revisar en la base de datos del Alto Rendimiento, para consultar el **Monto Total Línea**, obtenemos lo siguiente:

![image](https://cloud.githubusercontent.com/assets/5757157/18053991/7445c156-6dd8-11e6-8a28-86035c20e8a8.png)

Con lo cuál cuadra el monto, el que no me cuadra es el total de Seleccionado:

Al consultar, me aparece lo siguiente, tomando como estado de seleccionado el idworkflow=6:

![image](https://cloud.githubusercontent.com/assets/5757157/18054118/f1d8d4fa-6dd8-11e6-88fd-c47937d38f31.png)

Y en el reporte me aparece: 

![image](https://cloud.githubusercontent.com/assets/5757157/18054177/270c7186-6dd9-11e6-82cc-3853f931d8cd.png)


Luego en el monto Aprobado;

![image](https://cloud.githubusercontent.com/assets/5757157/18054318/c0537b0a-6dd9-11e6-98cb-306596fd8a34.png)

Y en el reporte:

![image](https://cloud.githubusercontent.com/assets/5757157/18054342/d82ac3b4-6dd9-11e6-826f-200db8a343f6.png)

@Pablo favor de aclararme de donde se leen esos montos  saludos

**Comment by felipedonoso** [comment]
@pabloespinoza coméntame en que estado a quedado este reporte, recuerdo que había unos problemas al momento de implementar  sí es así le recordamos a Andy sino hay que pasar esa pieza a producción. Ya que esto lo revise y esta OK.

**Comment by felipedonoso** [comment]
@pabloespinoza mira revisando el sitio en producción me encontré con lo siguiente:

### Al pinchar el botón me aparece esta URL:

![image](https://cloud.githubusercontent.com/assets/5757157/18710609/79e607ae-7fdc-11e6-87f9-0e1c574d5fd4.png)


**Al consultar por la línea:**

![image](https://cloud.githubusercontent.com/assets/5757157/18710659/c497d412-7fdc-11e6-93b5-69b4d48e3f75.png)

**Realice la siguiente consulta, en Producción:**

![image](https://cloud.githubusercontent.com/assets/5757157/18710736/19149462-7fdd-11e6-8b11-45928fff07da.png)

**Luego filtre todos los montos asociados a la línea número 7, acá se encuentran los Seleccionados + Aprobados para dicha línea:**

![image](https://cloud.githubusercontent.com/assets/5757157/18710874/b63ae570-7fdd-11e6-8c55-f127c9c24dfd.png)

Ahora consultado por la tabla proyecto por los que son Seleccionados de la misma línea observo lo siguiente:

![image](https://cloud.githubusercontent.com/assets/5757157/18711036/780fbce8-7fde-11e6-870e-6de6a222d66e.png)

**Entonces en el monto Seleccionado debería aparecer esto: $22.000.000**.

Y por último haciendo el mismo ejercicio pero con los Aprobados encuentro lo siguiente:

![image](https://cloud.githubusercontent.com/assets/5757157/18711133/dcff1c2a-7fde-11e6-92b0-d2d62fb593a8.png)

Y en Converges al consultar por los aprobados me entrego lo siguiente:

![image](https://cloud.githubusercontent.com/assets/5757157/18711325/cb3fac42-7fdf-11e6-86eb-135c45056c67.png)

Y en Converges al consultar por los Seleccionados no me arroja ningún resultado:

![image](https://cloud.githubusercontent.com/assets/5757157/18711353/eeb33a54-7fdf-11e6-8475-00001c4d2a2b.png)

**Comment by felipedonoso** [comment]
@pabloespinoza mira esto después hay que revisar los tiempos de sesión, lo ideal tanto para el exportar un PDF, siempre se maneje ese error de tiempo de sesión. Adjunto el error que me acaba de ocurrir al exportar a PDF.

![image](https://cloud.githubusercontent.com/assets/5757157/18750779/eedf4986-80b2-11e6-984a-f86f8e1dfa70.png)

**Comment by felipedonoso** [comment]
@pabloespinoza, al revisar el mantenedor de Cuentas, y la acción que hace Paillacar el analista encargado de Asignar recursos a las Federaciones, el carga el monto en la tabla CUENTA al parecer, entonces la duda que tengo y esto se pasa al tema de crear un proyecto para 2017, cuando el sistema no le permite postular un proyecto por qué ya sobrepaso el presupuesto. Cuando llegues lo revisamos por que al ver la Base de de datos, hay montos distintos entre la tabla **_Cuenta y Línea._**

**Comment by pabloespinoza** [comment]
@felipedonoso efectivamente, es la tabla cuenta la que se utiliza, el monto de la linea no se actualiza.
Cuando la federación desea postular un proyecto, el sistema valida con los montos de la tabla organizacion_linea y monto_organizacion_linea.

**Comment by pabloespinoza** [comment]
@felipedonoso efectivamente, es la tabla cuenta la que se utiliza, el monto de la linea no se actualiza.
Cuando la federación desea postular un proyecto, el sistema valida con los montos de la tabla organizacion_linea y monto_organizacion_linea.

**Comment by felipedonoso** [comment]
## Se pasa a producción y se revisa también en este ambiente logrando poder modificar la contraseña

**Comment by felipedonoso** [comment]
Se re abre esta tarea, se asignarán los estados de la SC: 11 y 12, con esto no ocurrirán los descuadres.

**Comment by felipedonoso** [comment]
@pabloespinoza como se reviso ayer habría que revisar el como lee el campo **MONTO** de la siguiente grilla:

![image](https://user-images.githubusercontent.com/5757157/29819127-a6183024-8c95-11e7-9bca-9bd0678730e2.png)

Lo que se puede concluir ayer de los casos de proyectos el 1700042288 y 1700042152, es que el campo proMonto de la tabla Proyecto, se guarda bien, pero habría que revisar al momento de SELECCIONAR un proyecto que ocurre.

Para esto se tomará el mismo caso del proyecto **1700042288**.

**Comment by felipedonoso** [comment]
@pabloespinoza, el error ocurrió al subir un documento de word en la parte de aprobación al guardar.

Al final se observa el error, mañana revisare los montos ya que con esto basta para ver el tema principal.

El documento:
[pasaporteGato.docx](https://github.com/InstitutoNacionalDeDeportes/AdministracionAltoRendimiento2017/files/1268333/pasaporteGato.docx)

**Comment by felipedonoso** [comment]
@pabloespinoza, resumiendo el proyecto se objeto en más de una oportunidad, desde la opción Volver atrás y desde la evaluación del proyecto.

En conclusión, el campo **promonto** solo se actualiza cuando se postula un proyecto, y también se observa un problema en el reporte, ya que al momento de que un proyecto lo deja en estado ingresado y uno modifico un gasto, en este caso lo elimino y en el reporte sigue apareciendo lo cual puede confundir al ANALISTA.

Las pruebas están realizas en:

https://github.com/InstitutoNacionalDeDeportes/PruebasINDVarias/issues/17

**Comment by felipedonoso** [comment]
@pabloespinoza 

# Conclusión:

**Esta listo para pasar a producción, lo único es el tema del reporte en la visualización la paginación, ya que no muestra el detalle del producto. Esto habría que estudiarlo posteriormente**

**Comment by felipedonoso** [comment]
# Esto ha quedado solucionado pasado a producción.
