### ISSUE TITLE
Administración - Objeción proyecto Seleccionado

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/AdministracionAltoRendimiento2017#21]
Esta prueba pretende ver el comportamiento de un proyecto que se **"Objeta"** específicamente cuando el proyecto se encuentra en estado **"Seleccionado"**.

**Comment by felipedonoso** [comment]
@pabloespinoza como lo conversamos al momento que se objeta un proyecto en estado seleccionado debe disminuir el campo **"molMontosAsignados"** de la tabla  **_montos_organizacion_linea_**

Y debe ir a borrar el registro en la tabla HDA_PROYECTO en Converges.

**Comment by felipedonoso** [comment]
Para esta prueba se revisará un proyecto en estado "Seleccionado" en Converges y que este en el mismo estado en la base de datos de QA AltoRendimiento.

**El proyecto de prueba será: 1600042195**

**_select * from hda_proyecto where proyecto like '1600042%' and estado=6_**

![image](https://cloud.githubusercontent.com/assets/5757157/19284612/099ca6fa-8fcd-11e6-8eb6-94f80bc5d266.png)

Y en SQL QA ALTORENDIMIENTO

_**select proFolioProyecto,proNombreProyecto,proMonto from proyecto where proFolioProyecto=201600042195**_

![image](https://cloud.githubusercontent.com/assets/5757157/19284824/d672a26a-8fcd-11e6-8cbf-f0a5ef3e454e.png)

Y en la tabla montos_organizacion_linea:

_**select * from montos_organizacion_linea where idOrganizacionlinea=313**_

![image](https://cloud.githubusercontent.com/assets/5757157/19284988/9e729aa4-8fce-11e6-8753-66149c3cd31b.png)


### Monto antes de la objeción:  142.437.976
## Monto después de la objeción:  142.437.976 - 13.740.000 =128.697.976

Volviendo atrás el proyecto:

![image](https://cloud.githubusercontent.com/assets/5757157/19285147/5df82b50-8fcf-11e6-9a34-76236e1cd594.png)

## Al revisar en Converges:

La prueba fue satisfactoria.

![image](https://cloud.githubusercontent.com/assets/5757157/19285205/958601fa-8fcf-11e6-8dec-9fb885d09955.png)


## Ahora en la tabla de SQL:

La prueba fue satisfactoria:

![image](https://cloud.githubusercontent.com/assets/5757157/19285632/15c3b712-8fd1-11e6-9519-96834dd47933.png)

### el monto coincide con lo esperado: 128.697.976

Solo hacer el alcance del correo enviado a la federación ya los demás integrantes no fue enviado.

Favor de revisar eso @pabloespinoza y resuelto eso damos por terminado esta tarea.

**Comment by felipedonoso** [comment]
@pabloespinoza me llego este correo:

![image](https://cloud.githubusercontent.com/assets/5757157/19286086/c7d6e04a-8fd2-11e6-8e5b-a62fd55f81a4.png)

Pero como se destaca en amarillo los campos no está acorde a lo que se Objeto como el texto, la fecha y otros.

**Comment by felipedonoso** [comment]
@pabloespinoza ¿esta lista la versión para QA?

**Comment by pabloespinoza** [comment]
@felipedonoso, @danteghirardelli, la versión se encuentra habilitada para realizar las pruebas en QA. http://10.15.1.51/AdministracionQA

**Comment by felipedonoso** [comment]
Revisando los proyectos en estado "Seleccionados" en converges QA y que se encuentren en SQL QA: encontramos el siguiente proyecto:

201600042150

![image](https://cloud.githubusercontent.com/assets/5757157/19484874/8eabc936-952f-11e6-99f5-4973a057cbe8.png)

### El total que lleva entre proyectos Seleccionados y Aprobados: 128.700.029

![image](https://cloud.githubusercontent.com/assets/5757157/19484966/e5fe90ba-952f-11e6-9d18-41ebc1ba3242.png)

**En la bandeja de Administración:**

![image](https://cloud.githubusercontent.com/assets/5757157/19485045/3042d172-9530-11e6-8347-611eac364ccd.png)

**Objetandolo:**

![image](https://cloud.githubusercontent.com/assets/5757157/19485086/55cce2fc-9530-11e6-892a-a57e723bdbb8.png)


**Bandeja de entrada:**

![image](https://cloud.githubusercontent.com/assets/5757157/19485133/7eb15612-9530-11e6-9916-3cec5248a55a.png)

### Revisando en la tabla montos:organizacion_linea: $ 128.700.023, se restaron los $6 pesos:

![image](https://cloud.githubusercontent.com/assets/5757157/19485196/afcc1a98-9530-11e6-94d2-3eadcc0db618.png)


### Ahora en Converges:

Se ha eliminado el registro:

![image](https://cloud.githubusercontent.com/assets/5757157/19485267/f9247bfe-9530-11e6-936a-65ae8cfbd645.png)


# Conclusión:

La prueba fue satisfactoria, habría que replicar esta prueba, estando objetando el proyecto en el proceso de rendición de cuentas, se deberá ingresar al menos 5 minutos antes al sitio y ver como se comporta.

@pabloespinoza mientras tanto deja el archivo necesario para la publicación de ser satisfactoria la prueba en la tarde se pasa a producción y creamos una prueba con IND en producción y de ser correcto se cierra esta tarea.

**Comment by felipedonoso** [comment]
@pabloespinoza ayúdame que faltaría por revisar ya que ayer realizamos pruebas simulando el proceso de Converges que estuviera corriendo y te mencione que habría que mostrar un pop-ups indicando que "Favor de esperar esta el proceso de rendiciones en ejecución" y esto quedaría en uba nueva tarea que involucraría todas las llamadas a Converges. Entonces dejando esa tarea pendiente que faltaría? aprobar un proyecto cuando este el proceso andando? o ya la realizamos y se me olvido.

De estar la prueba de Selección y aprobación lista hay que pasar el código a Andy para que lo pase a producción y realizamos la prueba con el rut de IND y de ser satisfactoria se cierra esta tarea.

**Comment by felipedonoso** [comment]
@pabloespinoza, hay que pasar a producción, se reviso la selección y aprobación y luego como lo mencione antes se mejorará el mensaje de "Inténtelo más tarde"

**Comment by felipedonoso** [comment]
@pabloespinoza , el paso a producción ha sido satisfactorio: 

1. Elimino el registro en Converges
2. Descontó el monto en la tabla montos_organizacion_linea

Se cierra esta tarea.
