### ISSUE TITLE
Revisión del WS Registro Civil

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/AdministracionAltoRendimiento2017#25]
@pabloespinoza, como primera tarea sería revisar el WS la llamada y la devolución que nos entrega basándose en el formulario desarrollado para los Beneficiarios para el Alto Rendimiento.

**Comment by felipedonoso** [comment]
@pabloespinoza como lo conversamos habría que levantar la grilla con todos los **_"Deportistas"_** que están asociados como **_"POR DEFINIR"_**,  debería traer todos los que están asociados al producto **_Participación en Competencias_** y con el nivel internacional.

Luego se implementarán los filtros como:

1. Por Federación
2. Por Nivel
3. Código proyecto (Folio)

**Comment by felipedonoso** [comment]
@pabloespinoza, adjunto las imágenes del prototipo

![1](https://cloud.githubusercontent.com/assets/5757157/18887055/024816c8-84c9-11e6-82a4-b57b3e9da6b5.png)
![2](https://cloud.githubusercontent.com/assets/5757157/18887056/0273fcc0-84c9-11e6-9223-0187520c517e.png)
![3](https://cloud.githubusercontent.com/assets/5757157/18887057/0279bfc0-84c9-11e6-99a6-c4075646a153.png)
![4](https://cloud.githubusercontent.com/assets/5757157/18887059/027dc070-84c9-11e6-8348-272cd6352a30.png)
![5](https://cloud.githubusercontent.com/assets/5757157/18887058/027c3534-84c9-11e6-862a-2f1c3bfa2290.png)

**Comment by pabloespinoza** [comment]
Se omitirá el tipo de gasto y monto de gasto por temas de tiempo y se continua con la grilla según lo acordado.

**Comment by felipedonoso** [comment]
@pabloespinoza, pude acceder y me metí a revisar el sitio desde el servidor donde esta Dante:

Realice la siguiente consulta para saber el total de Beneficiarios **_"POR DEFINIR"_** y me arrojo un total de 36 Deportistas:

### Esta es la consulta: 
**_select * from beneficiario where idBeneficiario in
(select idBeneficiario from beneficiario_producto_cargo where idCargo=47)
order by benRutBeneficiario_**

![image](https://cloud.githubusercontent.com/assets/5757157/19037904/2b9f6b36-894f-11e6-97b3-1573bc806849.png)



Ahora filtrare por el producto de nivel internacional:

_**select * from beneficiario where idBeneficiario in
(select idBeneficiario from beneficiario_producto_cargo where idCargo=47 and idProducto in(select idProducto from producto where idProductoNivel=2))
order by benRutBeneficiario**_

**Aparecen 05 deportistas en el Nivel Internacional.**

![image](https://cloud.githubusercontent.com/assets/5757157/19038466/fe5d37ea-8951-11e6-95b5-beaa95521850.png)


@pabloespinoza, sólo me falta el filtro por el **_tipo de producto_**, favor de indicarme como puedo leerlo.

**Comment by felipedonoso** [comment]
@pabloespinoza, pude acceder y me metí a revisar el sitio desde el servidor donde esta Dante:

Realice la siguiente consulta para saber el total de Beneficiarios **_"POR DEFINIR"_** y me arrojo un total de 05 Deportistas:

### Esta es la consulta: 
**_select * from beneficiario where idBeneficiario in
(select idBeneficiario from beneficiario_producto_cargo where idCargo=47)
order by benRutBeneficiario_**

![image](https://cloud.githubusercontent.com/assets/5757157/19037904/2b9f6b36-894f-11e6-97b3-1573bc806849.png)


**Ahora filtrare por el producto de nivel internacional:**

_**select * from beneficiario where idBeneficiario in
(select idBeneficiario from beneficiario_producto_cargo where idCargo=47 and idProducto in(select idProducto from producto where idProductoNivel=2))
order by benRutBeneficiario**_

**Aparecen 02 deportistas en el Nivel Internacional pero no son por Definir.**

![image](https://cloud.githubusercontent.com/assets/5757157/19038611/ab313c14-8952-11e6-9205-9641bbbda604.png)


@pabloespinoza, En resumen, si la consulta esta bien y la base de datos es "QA_Alto_Rendimiento":

![image](https://cloud.githubusercontent.com/assets/5757157/19038736/4a87d0de-8953-11e6-8146-070fef9416ac.png)

## No me estaría reflejando el mismo resultado el sistema:

 
![image](https://cloud.githubusercontent.com/assets/5757157/19038868/e79cebe8-8953-11e6-9bd0-f98d6a05b970.png)

@pabloespinoza, sólo me falta el filtro por el **_tipo de producto_**, favor de indicarme como puedo leerlo.

**Comment by felipedonoso** [comment]
@pabloespinoza como lo conversamos al momento de agregar a un beneficiario que no tenga disciplinas indicar un mensaje:

## "La Federación No tiene disciplinas asociadas", favor de regular este problema con los analistas de IND"

Debe mantener el mismo diseño que los cuadros de diálogo que los anteriores.

Lo otro cuando el beneficiario no este registrado por la Federación, deberá guardar al beneficiario por la primera disciplina que se encuentre, de no existir pasa al primer caso mensaje de error.

**Comment by felipedonoso** [comment]
**1.- Datos antes de **guardar:****

![image](https://cloud.githubusercontent.com/assets/5757157/19051411/620dd1fa-8989-11e6-9bf9-23250e519b9c.png)

Antes de grabar los registros:

![image](https://cloud.githubusercontent.com/assets/5757157/19051683/373808fa-898a-11e6-93eb-2da562055cea.png)

Si el beneficiario no existe debería agregar un nuevo registro en la tabla Beneficiario.

![image](https://cloud.githubusercontent.com/assets/5757157/19051770/91a68a0a-898a-11e6-8c5c-f6b624189b96.png)


La prueba fue satisfactoria, quedaría pendiente estos temas:

1. Eliminar la imagen de subir archivo sino existen beneficiarios por Definir.
2. Permitir actualizar Beneficiarios independientemente que otros registros no tengan disciplinas asociadas a su Federación.

Teniendo eso listo se pasa a producción.

**Comment by felipedonoso** [comment]
@danteghirardelli, favor de realizar pruebas en el Servidor que tienes al lado y como te mencione ingresa disntintos rut, las pruebas que tú sabes hacer y en distintos navegadores. El usuario a utilizar es en el sistema de Administración:

## RUT:153149682
Clave:Nov0915,

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 

Se comienza con las pruebas en Browser Google Chrome

![image](https://cloud.githubusercontent.com/assets/21196249/19073948/1f53465c-8a14-11e6-8ce8-1b99bd51b83f.png)

Se ingresa en campo un RUT válido
![image](https://cloud.githubusercontent.com/assets/21196249/19074044/927347cc-8a14-11e6-808d-6c91059ed216.png)

Se presiona la acción de validación(Editar)
![image](https://cloud.githubusercontent.com/assets/21196249/19074155/33cff566-8a15-11e6-8eb4-b80ae34cd61e.png)

Registro Civil despliega mensaje "Validar Rut Registro Civil"

Se ha validado el Rut, con la base de datos del Registro Civil con Éxito El rut corresponde a: DANTE JORGE GHIRARDELLI DONOSO

Con Botón "Aceptar"
![image](https://cloud.githubusercontent.com/assets/21196249/19074202/82db9ea8-8a15-11e6-9aa7-85548d79465a.png)

Grilla validada queda en color verde para Para Código de Proyecto 1600042072.

Como sugerencia la acción "Eliminar"(icono) se debe cambiar por acción "Limpiar". Se conversa este cambio con el Cliente.

En Grilla de Código de Proyecto "0" campo "RUT" se ingresan caracteres extraños
![image](https://cloud.githubusercontent.com/assets/21196249/19074608/5a26b8c4-8a17-11e6-8213-670cea291534.png)

Se sugiere no permitir el ingreso de dichos caracteres.

En Grilla de Código de Proyecto "0" campo "RUT" se intenta ingresar código HTML


```
<HTML>

<HEAD>

<TITLE>Un Titulo para el Browser de turno </TITLE>

</HEAD>

<BODY>

<!-- Aqui va todo lo chachi -->

<H1>Otro t&iacute;tulo, esta vez m&aacute;s largo. </H1>

<P> <IMG SRC= "./felix.gif "ALIGN= "MIDDLE " ALT= "EL Gato Felix ">Hoola.

<P>Esto es un parrafo con informacion

super importante. Notese que las lineas salen pegadas aun dejando

espacios, saltos de linea, etc. <BR> &#161 Si pongo esto

si <STRONG>cambia </STRONG> de linea!

<P>Otro parrafo, esto ya es un poco rollo.

<H3>Pongamos un subtítulo<H3>

<P>Por cierto, &#191 que paso con las <A HREF= "#pepe ">anclas</A>?

<HR>

<UL>

<LI> Esto es una lista no ordenada.

<LI> Las listas quedan mejor si tienen varios elementos.

</UL>

Me voy al <A HREF= "http://www.iac.es/home.html ">IAC</A>.

<P>Vamos a crear un <EM>ancla </EM>, o lo que es lo mismo, un <A NAME="pepe">anchor.</A>

```
![image](https://cloud.githubusercontent.com/assets/21196249/19074751/14ba3922-8a18-11e6-99e4-65143db67353.png)

Posteriormente se presiona acción "Editar"
![image](https://cloud.githubusercontent.com/assets/21196249/19074777/3a5993e4-8a18-11e6-979c-2275a4cda9dc.png)

Sistema despliega mensaje:
"Debe ingresar Rut válido"
Se sugiere no permitir ingreso de HTML

En Grilla de Código de Proyecto "0" campo "RUT" se ingresan letras.

![image](https://cloud.githubusercontent.com/assets/21196249/19074820/842ce5ac-8a18-11e6-9ffd-596a2d4b88e3.png)


Se presiona acción "Editar"
![image](https://cloud.githubusercontent.com/assets/21196249/19074939/0f948fb4-8a19-11e6-9124-dee0dfc23f64.png)

Se despliega mensaje:
"Debe ingresar Rut válido"

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 

Se comienza con las pruebas en Browser Explorer
![image](https://cloud.githubusercontent.com/assets/21196249/19076548/9d9a49ec-8a1f-11e6-9ce7-fd530b6bac6c.png)

Se ingresa en campo un RUT válido
![image](https://cloud.githubusercontent.com/assets/21196249/19076599/cf629cea-8a1f-11e6-85b8-2e9ec6f1d544.png)

Se presiona la acción de validación(Editar)
![image](https://cloud.githubusercontent.com/assets/21196249/19076631/fd9b21c2-8a1f-11e6-8de8-3cf9db060b32.png)

Registro Civil despliega mensaje "Validar Rut Registro Civil"

Se ha validado el Rut, con la base de datos del Registro Civil con Éxito El rut corresponde a: DANTE JORGE GHIRARDELLI DONOSO

Con Botón "Aceptar"
![image](https://cloud.githubusercontent.com/assets/21196249/19076679/30331df6-8a20-11e6-9bef-91ed3843a35b.png)

Grilla validada queda en color verde para Para Código de Proyecto 1600042072.

Como sugerencia la acción "Eliminar"(icono) se debe cambiar por acción "Limpiar". Se conversa este cambio con el Cliente.

En Grilla de Código de Proyecto "0" campo "RUT" se ingresan caracteres extraños.
`![image](https://cloud.githubusercontent.com/assets/21196249/19076809/a10d7986-8a20-11e6-8696-0b6ea86f479d.png)`

Se sugiere no permitir el ingreso de dichos caracteres.

En Grilla de Código de Proyecto "0" campo "RUT" se intenta ingresar código HTML


```
<HTML>

<HEAD>

<TITLE>Un Titulo para el Browser de turno </TITLE>

</HEAD>

<BODY>

<!-- Aqui va todo lo chachi -->

<H1>Otro t&iacute;tulo, esta vez m&aacute;s largo. </H1>

<P> <IMG SRC= "./felix.gif "ALIGN= "MIDDLE " ALT= "EL Gato Felix ">Hoola.

<P>Esto es un parrafo con informacion

super importante. Notese que las lineas salen pegadas aun dejando

espacios, saltos de linea, etc. <BR> &#161 Si pongo esto

si <STRONG>cambia </STRONG> de linea!

<P>Otro parrafo, esto ya es un poco rollo.

<H3>Pongamos un subtítulo<H3>

<P>Por cierto, &#191 que paso con las <A HREF= "#pepe ">anclas</A>?

<HR>

<UL>

<LI> Esto es una lista no ordenada.

<LI> Las listas quedan mejor si tienen varios elementos.

</UL>

Me voy al <A HREF= "http://www.iac.es/home.html ">IAC</A>.

<P>Vamos a crear un <EM>ancla </EM>, o lo que es lo mismo, un <A NAME="pepe">anchor.</A>
  


```

![image](https://cloud.githubusercontent.com/assets/21196249/19077037/607d6c18-8a21-11e6-9fe7-ccf80935c407.png)

Sistema despliega mensaje:
"Debe ingresar Rut válido"
Se sugiere no permitir ingreso de HTML

En Grilla de Código de Proyecto "0" campo "RUT" se ingresan letras.

![image](https://cloud.githubusercontent.com/assets/21196249/19077098/97a97c7c-8a21-11e6-8aa6-e27e79f000dd.png)

Se presiona acción "Editar"

![image](https://cloud.githubusercontent.com/assets/21196249/19077135/bd807888-8a21-11e6-9d80-064accc7d1fc.png)


Se despliega mensaje:
"Debe ingresar Rut válido".

**Comment by felipedonoso** [comment]
@pabloespinoza, una vez corregida las observaciones de Dante en particular esta:

**_Como sugerencia la acción "Eliminar"(icono) se debe cambiar por acción "Limpiar". Se conversa este cambio con el Cliente._**

Sería cambiar el texto al posicionarse sobre el icono de la papelera, "Limpiar" en vez de eliminar y así evitar que el usuario piense que eliminará el registro. También si existe un icono similar a este:

![image](https://cloud.githubusercontent.com/assets/5757157/19078073/4dd41504-8a25-11e6-892b-38212742702f.png)

Estaría bueno sino omitir.

Lo que conversamos ayer sobre los errores:

Del WS:

Todos los códigos devueltos con signo menor a "00", debería indicar algo como esto:

![image](https://cloud.githubusercontent.com/assets/5757157/19078210/c06114f0-8a25-11e6-9503-5915c4034dbb.png)


Luego seguir con los filtros, realizamos las pruebas y lo pasamos a producción.

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 

Se comienza con las pruebas en Browser Firefox
![image](https://cloud.githubusercontent.com/assets/21196249/19078267/f65a2920-8a25-11e6-9ee8-fcb3c702494a.png)

Se ingresa en campo un RUT válido
![image](https://cloud.githubusercontent.com/assets/21196249/19078314/1d4b5554-8a26-11e6-8e2e-287715ba3087.png)

Se presiona la acción de validación(Editar)
![image](https://cloud.githubusercontent.com/assets/21196249/19078347/4055f3ba-8a26-11e6-9716-7e0698dae7c7.png)

Registro Civil despliega mensaje "Validar Rut Registro Civil"

Se ha validado el Rut, con la base de datos del Registro Civil con Éxito El rut corresponde a: DANTE JORGE GHIRARDELLI DONOSO

Con Botón "Aceptar"

![image](https://cloud.githubusercontent.com/assets/21196249/19078439/7fcde0b6-8a26-11e6-8a12-ddd48cc2096d.png)


Grilla validada queda en color verde para Para Código de Proyecto 1600042072.

Como sugerencia la acción "Eliminar"(icono) se debe cambiar por acción "Limpiar". Se conversa este cambio con el Cliente.

En Grilla de Código de Proyecto "0" campo "RUT" se ingresan caracteres extraños.
![image](https://cloud.githubusercontent.com/assets/21196249/19078481/a3448770-8a26-11e6-9a34-ddce9b955d5b.png)

En Grilla de Código de Proyecto "0" campo "RUT" se intenta ingresar código HTML
![image](https://cloud.githubusercontent.com/assets/21196249/19078517/c9fc8e9e-8a26-11e6-9c56-066a1a6d618c.png)

```
<HTML>

<HEAD>

<TITLE>Un Titulo para el Browser de turno </TITLE>

</HEAD>

<BODY>

<!-- Aqui va todo lo chachi -->

<H1>Otro t&iacute;tulo, esta vez m&aacute;s largo. </H1>

<P> <IMG SRC= "./felix.gif "ALIGN= "MIDDLE " ALT= "EL Gato Felix ">Hoola.

<P>Esto es un parrafo con informacion

super importante. Notese que las lineas salen pegadas aun dejando

espacios, saltos de linea, etc. <BR> &#161 Si pongo esto

si <STRONG>cambia </STRONG> de linea!

<P>Otro parrafo, esto ya es un poco rollo.

<H3>Pongamos un subtítulo<H3>

<P>Por cierto, &#191 que paso con las <A HREF= "#pepe ">anclas</A>?

<HR>

<UL>

<LI> Esto es una lista no ordenada.

<LI> Las listas quedan mejor si tienen varios elementos.

</UL>

Me voy al <A HREF= "http://www.iac.es/home.html ">IAC</A>.

```
<P>Vamos a crear un <EM>ancla </EM>, o lo que es lo mismo, un <A NAME="pepe">anchor.</A>


![image](https://cloud.githubusercontent.com/assets/21196249/19078611/27b8861e-8a27-11e6-91f3-8aa21a7f515f.png)


Sistema despliega mensaje:
"Debe ingresar Rut válido"
Se sugiere no permitir ingreso de HTML

En Grilla de Código de Proyecto "0" campo "RUT" se ingresan letras.

![image](https://cloud.githubusercontent.com/assets/21196249/19078650/4624d7ce-8a27-11e6-80dc-0cdea486edbf.png)

Se presiona acción "Editar"

![image](https://cloud.githubusercontent.com/assets/21196249/19078670/52b5e5d2-8a27-11e6-8664-b013bc2da489.png)


Se despliega mensaje:
"Debe ingresar Rut válido".

**Comment by felipedonoso** [comment]
@pabloespinoza, como lo conversamos crear el filtro por **Federaciones**, y agregar  la siguiente glosa:

![image](https://cloud.githubusercontent.com/assets/5757157/19079280/7c00aa24-8a29-11e6-9b13-fb066a7d20ba.png)

**Comment by felipedonoso** [comment]
@pabloespinoza que al momento de guardar los beneficiarios, el botón grabar no valide que todos los registros estén completos, ejemplo si se le presenta una grilla de 10 beneficiarios que permita grabar 5.

**Comment by felipedonoso** [comment]
@pabloespinoza, damos por cerrado esta tarea y quedamos atentos a las posibles mejoras que necesite Daniela Arroyo.

Se adjunta imagen de Beneficiario por definir actualizado en producción.

![image](https://cloud.githubusercontent.com/assets/5757157/19126089/e9de9eb6-8b0f-11e6-9b09-a841152f66b8.png)
