### ISSUE TITLE
Línea PDA Administración

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/AdministracionAltoRendimiento2017#3]
Este problema ocurre que la línea definida para Administración del Alto Rendimiento es: **1212401341000**
pero el Converges la reconoce como la siguiente línea: **1212401341412**

Los pasos a seguir son:

Respaldar las tablas de converges:

- HDA_PROYECTO
- HDA_MOVIMIENTOS
- HDA_RENDICIONES
- HDA_SECRETARIA

Esto es solamente para los proyectos de administración. Esta tarea la realizare Yo.

Pablo habría que reemplazar en la tabla cuenta,  los números de línea. De manera similar para la línea del COCH.

Se adjunta respaldo de los proyectos afectados en la actualización PDA.

[HDARendiciones341000-341412.xlsx](https://github.com/InstitutoNacionalDeDeportes/AdministracionAltoRendimiento2017/files/435576/HDARendiciones341000-341412.xlsx)
[HDASecretaria341000-341412.xlsx](https://github.com/InstitutoNacionalDeDeportes/AdministracionAltoRendimiento2017/files/435577/HDASecretaria341000-341412.xlsx)
[HDAMovimientos341000-341412.xlsx](https://github.com/InstitutoNacionalDeDeportes/AdministracionAltoRendimiento2017/files/435578/HDAMovimientos341000-341412.xlsx)

**Comment by pabloespinoza** [comment]
Registros reemplazados.

**Comment by felipedonoso** [comment]
Proyectos corregidos se cierra el caso
