### ISSUE TITLE
Ver documentos adjuntos de los Beneficiarios/ Informe de Avance

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/AdministracionAltoRendimiento2017#31]
Esta tarea tiene como fin el poder visualizar los distintos documentos existentes de los beneficiarios en un proyecto puntual.

En la bandeja de entrada deberá existir un icono que indique ver documentos adjuntos:

**_Se utilizará el mismo icono de ver documentos del proyecto:_**

![image](https://cloud.githubusercontent.com/assets/5757157/19769373/8670fdf0-9c31-11e6-9b55-e1751fd576e2.png)
### Luego en la página que carga:

![image](https://cloud.githubusercontent.com/assets/5757157/19769416/a480de3c-9c31-11e6-9ccd-d2d96c6d2b77.png)

**_Debería quedar algo similar a esto:_**

![image](https://cloud.githubusercontent.com/assets/5757157/19769546/3d49aa18-9c32-11e6-9691-31499ba4d1d2.png)
1. Alinear información del proyecto como proyecto y código de proyecto.
2. Agregar botones al lado donde esta el botón volver: Documentos Beneficiarios y Informes de Avance/otros.
3. Búsqueda por Nombre 
### Campos Grilla Documentos Beneficiarios:
1. Rut/Pasaporte
2. Nombre
3. Cargo
4. Género
5. Deportista
6. Nacionalidad
7. Fecha Nacimiento
8. Acción

**Acción:**

Tendrá dos iconos:
Visualizar
Descargar

**Comment by pabloespinoza** [comment]
@felipedonoso Todo lo que se ingrese con la opción de tipo documento "Otros" quedara en la tabla de "Informe de avance / Otros"

**Comment by felipedonoso** [comment]
Se ha revisado la carga de archivo y la visualización y estaría Ok, queda revisar la parte de administración.

**Visualizando los archivos:**

![image](https://cloud.githubusercontent.com/assets/5757157/19926884/eeb758b6-a0d5-11e6-9adc-4361dada766c.png)

**Y al descargar el archivo:**

![image](https://cloud.githubusercontent.com/assets/5757157/19926892/ff37ce50-a0d5-11e6-89c6-aac5885343df.png)

**Comment by pabloespinoza** [comment]
@felipedonoso @danteghirardelli las mejoras se encuentran publicadas en QA.

http://10.15.1.51/AdministracionQA

**Comment by felipedonoso** [comment]
@pabloespinoza lo que habría que hacer es que al momento de obtener todos los Beneficiarios deberá hacer un distinct por Beneficiario, ya que puede estar ingresado en más de un producto en el mismo proyecto y se repetiría el registro sólo cuando tenga distintos documentos:

![image](https://cloud.githubusercontent.com/assets/5757157/19941532/3680d12a-a10f-11e6-8e57-d5c37a9a4780.png)


**_Entonces: debería aparecer 02 veces Aldo Garrido con los siguientes documentos:_**

1. Curriculum Vitae
2. Certificado de la Federación

**Lo otro sería ver si al ser muchos registros se cargará en una grilla**

**Comment by pabloespinoza** [comment]
@felipedonoso @danteghirardelli Se elimina la columna Cargo para que no se produzca duplicidad en los datos. La solucion se encuentra publicada en QA. 

http://10.15.1.51/AdministracionQA

**Comment by felipedonoso** [comment]
Revisando en la bandeja de administración:

![image](https://cloud.githubusercontent.com/assets/5757157/19965226/bfd5ed44-a1a4-11e6-913e-51729cd8e0f5.png)

Se agrega a un deportista:
![image](https://cloud.githubusercontent.com/assets/5757157/19965388/810cf5a2-a1a5-11e6-81bb-b564140ef2eb.png)


Se le sube un documento, ya que no tenía:
![image](https://cloud.githubusercontent.com/assets/5757157/19965330/44b2c2b2-a1a5-11e6-90bb-4909fde2f8c6.png)

Se agregan nuevos beneficiarios, un total de 11 y uno que es por definir :

![image](https://cloud.githubusercontent.com/assets/5757157/19965937/22532506-a1a8-11e6-928d-942e5921ef62.png)

**Al buscar en la bandeja de administración no aparecen los nuevos Beneficiarios:**
![image](https://cloud.githubusercontent.com/assets/5757157/19966264/c0af2d7a-a1a9-11e6-983c-02c890ef78e2.png)

**_Pensé que podría ser por motivos de que no tiene documentos adjuntos pero si los tienen:_**

![image](https://cloud.githubusercontent.com/assets/5757157/19966305/e9601dec-a1a9-11e6-800c-01f36f84ce80.png)


**_Lo otro puede ser por motivos de que están en rojo y al revisar aparece el beneficiario por Definir._**

**Comment by pabloespinoza** [comment]
@felipedonoso Hay beneficiarios que no se muestran debido a que estos no tienen documentos adjuntos.

Por otro lado, se cambia la validación del campo "Deportista" 1 = No y 0 = Si y quita la hora en el campo "Fecha Nacimiento"

![image](https://cloud.githubusercontent.com/assets/21196998/19970871/1a1d259e-a1bc-11e6-98dc-e8645e660d8e.png)

**Comment by felipedonoso** [comment]
Se revisa por el lado de postulación:

![image](https://cloud.githubusercontent.com/assets/5757157/19980390/94602a84-a1dc-11e6-9c12-fddf6f066b45.png)

Ahora en el sistema de Administración:

![image](https://cloud.githubusercontent.com/assets/5757157/19980579/56eaf5ca-a1dd-11e6-81d7-6c0eb6d41850.png)


### Los que no aparecen:
![image](https://cloud.githubusercontent.com/assets/5757157/19980666/b0625d00-a1dd-11e6-97a6-684b41ec9e5f.png)

![image](https://cloud.githubusercontent.com/assets/5757157/19980935/aa5b6c02-a1de-11e6-9a1a-8156b5901ba5.png)

![image](https://cloud.githubusercontent.com/assets/5757157/19981017/e2d24b3c-a1de-11e6-9a48-9585cd9e6c32.png)

![image](https://cloud.githubusercontent.com/assets/5757157/19981062/1cd4fd20-a1df-11e6-8ad0-c3653bb3fc42.png)

**Faltaría por revisar la columna Deportista que no debería aparecer.**

**Comment by felipedonoso** [comment]
@pabloespinoza la revisión fue correcta se elimino la tabla Deportista y la fecha en la bandeja de entrada, favor de dejar el compilado para pasar a producción y hacer la revisión el producción para cerrar esta tarea.

**Comment by felipedonoso** [comment]
# ## Se revisa en producción y ha quedado OK se cierra la tarea.
