### ISSUE TITLE
Bandeja de Entrada - Fecha del proyecto 

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/AdministracionAltoRendimiento2017#32]
El error ocurre al mostrar la fecha del estado del proyecto en la bandeja de administración. Debe coincidir con la que se tiene el registro en la base de datos y debe ser igual al último registro en el Histórico de estados del proyecto.

### Bandeja de entrada:

Como se aprecia en la siguiente imagen tiene como fecha: **_Aprobada (08-09-2016 16:00:32)_**

![image](https://cloud.githubusercontent.com/assets/5757157/19942457/9233c74a-a112-11e6-83d7-ee751a69e34f.png)

Y en el histórico se aprecia la siguiente fecha:  **_29-09-2016 05:00:41 pm_**

![image](https://cloud.githubusercontent.com/assets/5757157/19942509/bec22dce-a112-11e6-968d-b4cdd37b20db.png)

En conclusión la fecha debe corresponder cuando se realizo la acción o dicho de otro modo el cambio de estado.

**Comment by pabloespinoza** [comment]
@felipedonoso @danteghirardelli El cambio se encuentra publicado en QA.

http://10.15.1.51/AdministracionQA

**Comment by felipedonoso** [comment]
**Revisando en la bandeja de entrada:**

![image](https://cloud.githubusercontent.com/assets/5757157/20112608/d0d1811e-a5cb-11e6-8a40-97adabd00169.png)

**Luego en el historial del proyecto:**

![image](https://cloud.githubusercontent.com/assets/5757157/20112636/ec6331de-a5cb-11e6-8a72-a2f5d328baa1.png)

@pabloespinoza Se revisa y esta OK en QA listo para pasar a producción.

**Comment by felipedonoso** [comment]
# Se revisa en producción y se cierra esta tarea
