### ISSUE TITLE
Link Crear Concurso

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/AdministracionAltoRendimiento2017#51]
En esta tarea se creará la opción **"Crear Concurso"**, esto solo será disponible desde el perfil **"ANALISTA/PRESUPUESTO"**.

Al hacer se presentará la siguiente interfaz:

![mesa de trabajo 6](https://user-images.githubusercontent.com/5757157/30972425-dc2026d2-a440-11e7-82a9-3362a3ff8204.png)

### Acciones:

**Botón Crear concurso:**

Este botón solamente, dará el paso al paso número 01.

**Comment by pabloespinoza** [comment]
Ademas de lo indicado por Felipe Donoso, se agrega que la pantalla debe listar los concursos con su nombre, inicio y fin de concurso, y el estado.
los estados posibles son:
- Inactivo.
- Activo.
- Pendiente.
Para los concursos en estado pendiente, para poder completarlos se debe presionar sobre el texto Pendiente para acceder a continuar con el proceso faltante.

**Comment by felipedonoso** [comment]
@pabloespinoza , @danteghirardelli compañeros como lo conversamos estas sería las reglas:

### 1. Solo se podrá crear un solo concurso.
### 2. Una vez autorizado el concurso, no podrá realizar modificaciones el usuario, solamente podrá comunicarse con informática para volver a bajar dicho concurso.

**Comment by felipedonoso** [comment]
@pabloespinoza , @danteghirardelli , como lo conversamos y según dictado por el Sr: Dante, al momento de ingresar los montos asociados a las Federaciones por Linea, debería insertar en la BD, todos los productos que existan.

**NOTA:** Para la Línea de PDA **"Art. 1º ley 19135 Fed. Dep. Nacional"**

**Comment by felipedonoso** [comment]
@pabloespinoza , @danteghirardelli , como lo detecto Dante y menciono Pablo al momento de validar las **fechas de inicio y de termino** en la jornada de un Beneficiario, **se deberá considerar los rangos de fecha del Concurso al cual pertenece el proyecto**.

**Comment by felipedonoso** [comment]
**Concursos:**

![image](https://user-images.githubusercontent.com/5757157/34483382-ddf7346c-ef9c-11e7-979f-2054837bfced.png)

En la BD:

![image](https://user-images.githubusercontent.com/5757157/34483652-ab5dc064-ef9e-11e7-9b42-12311029e904.png)


NOTA: Se pondrá atención en los concursos activos que tengan fecha posterior al año en curso, ya que si bien están activos, no se deberían desplegar por la fecha de inicio y fin.

Entrando al sitio de **POSTULACIÓN**:

![captura de pantalla 2018-01-02 a la s 09 38 09](https://user-images.githubusercontent.com/5757157/34484009-c1c4c8aa-efa0-11e7-83cf-5a1c5dcd6781.png)

Al listar los concurso solamente deberían desplegarse los que cumplan con la fecha de inicio y fin y que sean activos:

![image](https://user-images.githubusercontent.com/5757157/34484070-252cc85c-efa1-11e7-9bdb-ed2686aa0e01.png)

### **NOTA: En este caso no me debería permitir crear un nuevo proyecto.**

1. Al seleccionar el concurso no aparece la línea de financiamiento, lo cual se presta para confusiones entendiendo que es un error de plataforma.

2. Esto no debería poder ocurrir ya que el sistema pide al menos una linea de financiamiento en el paso previo a Autorizar.


![captura de pantalla 2018-01-02 a la s 09 43 25](https://user-images.githubusercontent.com/5757157/34484118-7236a5a0-efa1-11e7-97e0-45afe2e5a5fe.png)

Esto pudo haber ocurrido quizás a un error dentro de las pruebas.

Entonces ahora se intentará con el proyecto con vigencia en el año 2018:

**Se pudo crear sin problemas:**

![image](https://user-images.githubusercontent.com/5757157/34485221-23803410-efa8-11e7-85cf-45e71a6165d6.png)

**Comment by felipedonoso** [comment]
### Creando un concurso 2018:

Como se había conversado, con @pabloespinoza y @danteghirardelli, solamente se podrá crear un proyecto por año debido al plazo que hay para esta tarea.

![image](https://user-images.githubusercontent.com/5757157/34485377-0ab8e62e-efa9-11e7-8c33-42d6ce5852f3.png)

Se desactivará el concurso 2018 mediante BD:

```
update concurso
set conEstado=0
where idConcurso=34

Concurso:  2018	MUSTAFA 2018
```
Al actualizar en la plataforma:

No se aprecia el concurso **MUSTAFA**:

![image](https://user-images.githubusercontent.com/5757157/34485461-9dedfcea-efa9-11e7-90ee-df18415ef6c4.png)

**Comment by felipedonoso** [comment]
### PASO 2:

Realiza una lectura de las siguientes lineas:

![image](https://user-images.githubusercontent.com/5757157/34485726-d21eea50-efaa-11e7-9a53-1c83fb6cda2b.png)

Se debería revisar las lineas de concurso anterior:

La consulta entrega lo mismo que en la plataforma:

```
select --linpresupuesto,
ctaNombreCuenta,ctaPresupuestoVigente
from programa p
inner join linea l On p.idprograma=l.idprograma
inner join linea_cuenta lc On l.idlinea=lc.idlinea
inner join cuenta c on lc.idcuenta= c.idcuenta
where p.prgEstado=1 and l.linestado=1 and lc.lcuestado=1 and c.ctaestado=1 and p.prgano=2017
```

![image](https://user-images.githubusercontent.com/5757157/34486044-95f37f9e-efac-11e7-9976-d0110bb96c20.png)


**NOTA:**  Se observa que aparece un monto asignado **12.900.000.989**

![image](https://user-images.githubusercontent.com/5757157/34486095-d1e5c890-efac-11e7-906b-b149366d2669.png)

Esto no debería aparecer desde un inicio, así que se eliminará este concurso y se hará uno nuevo.

**Comment by felipedonoso** [comment]
**Eliminando el concurso:**

![image](https://user-images.githubusercontent.com/5757157/34486151-14ff0f7e-efad-11e7-9b7e-82a9a601d599.png)

Ahora de cero se creará otro concurso para eliminar posibles errores anteriores:

![image](https://user-images.githubusercontent.com/5757157/34486184-4d00b706-efad-11e7-992e-a4c0d34f0f86.png)

Ahora se puede observar correctamente el **PASO 2:**

### Falta una alerta o una Glosa indicando que  debe validar el nuevo presupuesto haciendo click en la figura **✓**

Se presiona Siguiente y pasa al Paso 3, se continuará hasta el final para ver su comportamiento.

![image](https://user-images.githubusercontent.com/5757157/34486285-dfde2e5a-efad-11e7-9b39-3addf7126a0c.png)

**Guardando los datos del PASO 2:**

@pabloespinoza me explica que debido a que es un programa no creado en QA, se presenta este error al crear la linea, ya que al crearla se necesita el id del programa:

![image](https://user-images.githubusercontent.com/5757157/34486343-378b2a9a-efae-11e7-9eff-1a5f1247ade2.png)

**Comment by felipedonoso** [comment]
### PASO  3:

Aparece la lista con las lineas creadas en el paso Anterior:

![image](https://user-images.githubusercontent.com/5757157/34486793-32b7288c-efb0-11e7-9af5-ed99bef5d080.png)

El filtro funciona en la celda **BUSCAR**:

![image](https://user-images.githubusercontent.com/5757157/34486831-5bf1430e-efb0-11e7-8d71-26316735bbc0.png)

**Asignado Presupuesto:**

El sistema Valida los montos de linea:

![image](https://user-images.githubusercontent.com/5757157/34486854-821bbbfe-efb0-11e7-8dcb-ee3ff476ae1a.png)

Los mensajes están correctos:

![image](https://user-images.githubusercontent.com/5757157/34486870-98ec00b4-efb0-11e7-8b73-45077ea92b5b.png)

![image](https://user-images.githubusercontent.com/5757157/34486919-d0f201e8-efb0-11e7-9f87-cc1dd9f0e4d8.png)

**Comment by felipedonoso** [comment]
### PASO 4:

![image](https://user-images.githubusercontent.com/5757157/34486957-fb02c792-efb0-11e7-9495-310d0f684c1d.png)

**Validando el concurso:**
![image](https://user-images.githubusercontent.com/5757157/34487016-2bbc74d2-efb1-11e7-8c23-51a079c0af4e.png)

Revisando en **postulación**:

![captura de pantalla 2018-01-02 a la s 11 37 56](https://user-images.githubusercontent.com/5757157/34487081-7c49b220-efb1-11e7-98a5-19428e669d5c.png)

Esto esta ok, debido que solamente el COCH, se le asigno presupuesto. Y la prueba se realizo con al federación: **ANDINISMO**

```
UPDATE usuario
SET IDORGANIZACION=104
WHERE USUrUT='16645373'

```
### Ahora como COCH, se puede apreciar la linea:

![image](https://user-images.githubusercontent.com/5757157/34487199-0556c0c6-efb2-11e7-965c-e2f049a12e16.png)

**Comment by felipedonoso** [comment]
# CONCLUSIÓN:

Se han resuelto las siguientes tareas:

https://github.com/InstitutoNacionalDeDeportes/AdministracionAltoRendimiento2017/issues/54
https://github.com/InstitutoNacionalDeDeportes/AdministracionAltoRendimiento2017/issues/53
https://github.com/InstitutoNacionalDeDeportes/AdministracionAltoRendimiento2017/issues/52

Favor @pabloespinoza , de dejar el código necesario para pasar a producción.

**NOTA: Excelente trabajo señores.**

**Comment by felipedonoso** [comment]
PASANDO a PRODUCCIÓN

**AltoRendimiento:**

![image](https://user-images.githubusercontent.com/5757157/34487643-0103eb6e-efb4-11e7-9bc4-c53d605ed606.png)

**Administración:**

![image](https://user-images.githubusercontent.com/5757157/34487696-3b0ff71c-efb4-11e7-9378-6e970462bf3d.png)


Se pasa a producción sin problemas:
