### ISSUE TITLE
Crear proyecto para Solicitud de Cambio

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/AdministracionAltoRendimiento2017#7]
La idea será crear un proyecto con Producto en PDE (Planes de desarrollo Estratégico), Apoyo especial a deportistas y Administración.

@danteghirardelli amigo usted creará un proyecto de **Administración** :+1:  Cómo el siguiente reporte:
[Proyecto - 1600042012.pdf](https://github.com/InstitutoNacionalDeDeportes/AdministracionAltoRendimiento2017/files/463922/Proyecto.-.1600042012.pdf)

Yo creare un proyecto de Planes de desarrollo estratégico: Cómo el siguiente:

[Proyecto - 1600042234.pdf](https://github.com/InstitutoNacionalDeDeportes/AdministracionAltoRendimiento2017/files/463943/Proyecto.-.1600042234.pdf)

Esta será la primera tarea.

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 
 
Felipe se creó Proyecto Dr Strange con Código 1600042194  en estado Postulado.
Adjunto 
[Proyecto - 1600042194_Antes SC.pdf](https://github.com/InstitutoNacionalDeDeportes/AdministracionAltoRendimiento2017/files/464179/Proyecto.-.1600042194_Antes.SC.pdf)
PDF Reporte

**Comment by felipedonoso** [comment]
De acuerdo a lo informado por @danteghirardelli  se ha creado el proyecto:

Felipe,
Buenas tardes.

Tengo listo el otro Proyecto "Stan Lee" para que lo postules y lo revisemos.
Atte.;

## Se da por terminada esta tarea que consistía en crear los proyectos necesarios para las pruebas.
